version: "2"

services:
  registry:
    image: "registry:2"
    ports:
      - 5000:5000

  test:
    image: "mlt"
    depends_on:
    #   - "kubernetes"
      - "registry"
    environment:
      # - KUBECONFIG=/usr/share/mlt/resources/config.yaml
      # not using /root/.kube/config because mlt will come with a blank config there
      - KUBECONFIG=/root/.gcloudkube/config
    command: "sleep inf"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/circleci/.kube/config:/root/.gcloudkube/config
